package com.stuman.domain;

import java.util.HashSet;
import java.util.Set;

/**
 * Computer generated by MyEclipse Persistence Tools
 */

public class Computer implements java.io.Serializable {

	// Fields

	private ComputerId id;

	private Labroom labroom;

	private String status;

	private String ip;

	private Set computeruses = new HashSet(0);

	// Constructors

	/** default constructor */
	public Computer() {
	}

	/** minimal constructor */
	public Computer(ComputerId id, Labroom labroom, String status, String ip) {
		this.id = id;
		this.labroom = labroom;
		this.status = status;
		this.ip = ip;
	}

	/** full constructor */
	public Computer(ComputerId id, Labroom labroom, String status, String ip,
			Set computeruses) {
		this.id = id;
		this.labroom = labroom;
		this.status = status;
		this.ip = ip;
		this.computeruses = computeruses;
	}

	// Property accessors

	public ComputerId getId() {
		return this.id;
	}

	public void setId(ComputerId id) {
		this.id = id;
	}

	public Labroom getLabroom() {
		return this.labroom;
	}

	public void setLabroom(Labroom labroom) {
		this.labroom = labroom;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public Set getComputeruses() {
		return this.computeruses;
	}

	public void setComputeruses(Set computeruses) {
		this.computeruses = computeruses;
	}

}