package com.stuman.domain;

import java.util.Date;

/**
 * ComputeruseId generated by MyEclipse Persistence Tools
 */

public class ComputeruseId implements java.io.Serializable {

	// Fields

	private String stuId;

	private String roomId;

	private String computerId;

	private Date startTime;

	private Date endTime;

	private Double duration;

	private Double cost;

	// Constructors

	/** default constructor */
	public ComputeruseId() {
	}

	/** full constructor */
	public ComputeruseId(String stuId, String roomId, String computerId,
			Date startTime, Date endTime, Double duration, Double cost) {
		this.stuId = stuId;
		this.roomId = roomId;
		this.computerId = computerId;
		this.startTime = startTime;
		this.endTime = endTime;
		this.duration = duration;
		this.cost = cost;
	}

	// Property accessors

	public String getStuId() {
		return this.stuId;
	}

	public void setStuId(String stuId) {
		this.stuId = stuId;
	}

	public String getRoomId() {
		return this.roomId;
	}

	public void setRoomId(String roomId) {
		this.roomId = roomId;
	}

	public String getComputerId() {
		return this.computerId;
	}

	public void setComputerId(String computerId) {
		this.computerId = computerId;
	}

	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public Double getDuration() {
		return this.duration;
	}

	public void setDuration(Double duration) {
		this.duration = duration;
	}

	public Double getCost() {
		return this.cost;
	}

	public void setCost(Double cost) {
		this.cost = cost;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ComputeruseId))
			return false;
		ComputeruseId castOther = (ComputeruseId) other;

		return ((this.getStuId() == castOther.getStuId()) || (this.getStuId() != null
				&& castOther.getStuId() != null && this.getStuId().equals(
				castOther.getStuId())))
				&& ((this.getRoomId() == castOther.getRoomId()) || (this
						.getRoomId() != null
						&& castOther.getRoomId() != null && this.getRoomId()
						.equals(castOther.getRoomId())))
				&& ((this.getComputerId() == castOther.getComputerId()) || (this
						.getComputerId() != null
						&& castOther.getComputerId() != null && this
						.getComputerId().equals(castOther.getComputerId())))
				&& ((this.getStartTime() == castOther.getStartTime()) || (this
						.getStartTime() != null
						&& castOther.getStartTime() != null && this
						.getStartTime().equals(castOther.getStartTime())))
				&& ((this.getEndTime() == castOther.getEndTime()) || (this
						.getEndTime() != null
						&& castOther.getEndTime() != null && this.getEndTime()
						.equals(castOther.getEndTime())))
				&& ((this.getDuration() == castOther.getDuration()) || (this
						.getDuration() != null
						&& castOther.getDuration() != null && this
						.getDuration().equals(castOther.getDuration())))
				&& ((this.getCost() == castOther.getCost()) || (this.getCost() != null
						&& castOther.getCost() != null && this.getCost()
						.equals(castOther.getCost())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getStuId() == null ? 0 : this.getStuId().hashCode());
		result = 37 * result
				+ (getRoomId() == null ? 0 : this.getRoomId().hashCode());
		result = 37
				* result
				+ (getComputerId() == null ? 0 : this.getComputerId()
						.hashCode());
		result = 37 * result
				+ (getStartTime() == null ? 0 : this.getStartTime().hashCode());
		result = 37 * result
				+ (getEndTime() == null ? 0 : this.getEndTime().hashCode());
		result = 37 * result
				+ (getDuration() == null ? 0 : this.getDuration().hashCode());
		result = 37 * result
				+ (getCost() == null ? 0 : this.getCost().hashCode());
		return result;
	}

}