package com.stuman.domain;

/**
 * Computeruse generated by MyEclipse Persistence Tools
 */

public class Computeruse implements java.io.Serializable {

	// Fields

	private ComputeruseId id;

	private Computer computer;

	private Student student;

	// Constructors

	/** default constructor */
	public Computeruse() {
	}

	/** full constructor */
	public Computeruse(ComputeruseId id, Computer computer, Student student) {
		this.id = id;
		this.computer = computer;
		this.student = student;
	}

	// Property accessors

	public ComputeruseId getId() {
		return this.id;
	}

	public void setId(ComputeruseId id) {
		this.id = id;
	}

	public Computer getComputer() {
		return this.computer;
	}

	public void setComputer(Computer computer) {
		this.computer = computer;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

}