package com.stuman.domain;

/**
 * ComputerId generated by MyEclipse Persistence Tools
 */

public class ComputerId implements java.io.Serializable {

	// Fields

	private String roomId;

	private String id;

	// Constructors

	/** default constructor */
	public ComputerId() {
	}

	/** full constructor */
	public ComputerId(String roomId, String id) {
		this.roomId = roomId;
		this.id = id;
	}

	// Property accessors

	public String getRoomId() {
		return this.roomId;
	}

	public void setRoomId(String roomId) {
		this.roomId = roomId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ComputerId))
			return false;
		ComputerId castOther = (ComputerId) other;

		return ((this.getRoomId() == castOther.getRoomId()) || (this
				.getRoomId() != null
				&& castOther.getRoomId() != null && this.getRoomId().equals(
				castOther.getRoomId())))
				&& ((this.getId() == castOther.getId()) || (this.getId() != null
						&& castOther.getId() != null && this.getId().equals(
						castOther.getId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getRoomId() == null ? 0 : this.getRoomId().hashCode());
		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		return result;
	}

}