package com.stuman.domain;

import java.util.HashSet;
import java.util.Set;

/**
 * Course generated by MyEclipse Persistence Tools
 */

public class Course implements java.io.Serializable {

	// Fields

	private String id;

	private String name;

	private String departmentId;

	private Integer credit;

	private String stuNumber;

	private Set courselists = new HashSet(0);

	// Constructors

	/** default constructor */
	public Course() {
	}

	/** minimal constructor */
	public Course(String id, String departmentId, Integer credit,
			String stuNumber) {
		this.id = id;
		this.departmentId = departmentId;
		this.credit = credit;
		this.stuNumber = stuNumber;
	}

	/** full constructor */
	public Course(String id, String name, String departmentId, Integer credit,
			String stuNumber, Set courselists) {
		this.id = id;
		this.name = name;
		this.departmentId = departmentId;
		this.credit = credit;
		this.stuNumber = stuNumber;
		this.courselists = courselists;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(String departmentId) {
		this.departmentId = departmentId;
	}

	public Integer getCredit() {
		return this.credit;
	}

	public void setCredit(Integer credit) {
		this.credit = credit;
	}

	public String getStuNumber() {
		return this.stuNumber;
	}

	public void setStuNumber(String stuNumber) {
		this.stuNumber = stuNumber;
	}

	public Set getCourselists() {
		return this.courselists;
	}

	public void setCourselists(Set courselists) {
		this.courselists = courselists;
	}

}