package com.stuman.domain;

import java.util.HashSet;
import java.util.Set;

/**
 * Course generated by MyEclipse Persistence Tools
 */

public class Course implements java.io.Serializable {

	// Fields

	private String id;

	private Teacher teacher;

	private String name;

	private String departmentId;

	private String classes;

	private Set courselists = new HashSet(0);

	// Constructors

	/** default constructor */
	public Course() {
	}

	/** minimal constructor */
	public Course(String id, Teacher teacher, String departmentId,
			String classes) {
		this.id = id;
		this.teacher = teacher;
		this.departmentId = departmentId;
		this.classes = classes;
	}

	/** full constructor */
	public Course(String id, Teacher teacher, String name, String departmentId,
			String classes, Set courselists) {
		this.id = id;
		this.teacher = teacher;
		this.name = name;
		this.departmentId = departmentId;
		this.classes = classes;
		this.courselists = courselists;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Teacher getTeacher() {
		return this.teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(String departmentId) {
		this.departmentId = departmentId;
	}

	public String getClasses() {
		return this.classes;
	}

	public void setClasses(String classes) {
		this.classes = classes;
	}

	public Set getCourselists() {
		return this.courselists;
	}

	public void setCourselists(Set courselists) {
		this.courselists = courselists;
	}

}