package com.stuman.domain;

/**
 * Courselist generated by MyEclipse Persistence Tools
 */

public class Courselist implements java.io.Serializable {

	// Fields

	private CourselistId id;

	private Course course;

	private Teacher teacher;

	// Constructors

	/** default constructor */
	public Courselist() {
	}

	/** full constructor */
	public Courselist(CourselistId id, Course course, Teacher teacher) {
		this.id = id;
		this.course = course;
		this.teacher = teacher;
	}

	// Property accessors

	public CourselistId getId() {
		return this.id;
	}

	public void setId(CourselistId id) {
		this.id = id;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public Teacher getTeacher() {
		return this.teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

}