package com.stuman.domain;

/**
 * Courselist generated by MyEclipse Persistence Tools
 */

public class Courselist implements java.io.Serializable {

	// Fields

	private CourselistId id;

	private Course course;

	private Teacher teacher;

	private Labroom labroom;

	private String startTime;

	private String endTime;

	// Constructors

	/** default constructor */
	public Courselist() {
	}

	/** full constructor */
	public Courselist(CourselistId id, Course course, Teacher teacher,
			Labroom labroom, String startTime, String endTime) {
		this.id = id;
		this.course = course;
		this.teacher = teacher;
		this.labroom = labroom;
		this.startTime = startTime;
		this.endTime = endTime;
	}

	// Property accessors

	public CourselistId getId() {
		return this.id;
	}

	public void setId(CourselistId id) {
		this.id = id;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public Teacher getTeacher() {
		return this.teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

	public Labroom getLabroom() {
		return this.labroom;
	}

	public void setLabroom(Labroom labroom) {
		this.labroom = labroom;
	}

	public String getStartTime() {
		return this.startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	public String getEndTime() {
		return this.endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

}