package com.stuman.domain;

import java.util.HashSet;
import java.util.Set;

/**
 * Labroom generated by MyEclipse Persistence Tools
 */

public class Labroom implements java.io.Serializable {

	// Fields

	private String id;

	private String capacity;

	private String computerNum;

	private String status;

	private Double cost;

	private Set computers = new HashSet(0);

	// Constructors

	/** default constructor */
	public Labroom() {
	}

	/** minimal constructor */
	public Labroom(String id, String capacity, String computerNum,
			String status, Double cost) {
		this.id = id;
		this.capacity = capacity;
		this.computerNum = computerNum;
		this.status = status;
		this.cost = cost;
	}

	/** full constructor */
	public Labroom(String id, String capacity, String computerNum,
			String status, Double cost, Set computers) {
		this.id = id;
		this.capacity = capacity;
		this.computerNum = computerNum;
		this.status = status;
		this.cost = cost;
		this.computers = computers;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getCapacity() {
		return this.capacity;
	}

	public void setCapacity(String capacity) {
		this.capacity = capacity;
	}

	public String getComputerNum() {
		return this.computerNum;
	}

	public void setComputerNum(String computerNum) {
		this.computerNum = computerNum;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Double getCost() {
		return this.cost;
	}

	public void setCost(Double cost) {
		this.cost = cost;
	}

	public Set getComputers() {
		return this.computers;
	}

	public void setComputers(Set computers) {
		this.computers = computers;
	}

}