package com.stuman.domain;

import java.util.HashSet;
import java.util.Set;

/**
 * Labroom generated by MyEclipse Persistence Tools
 */

public class Labroom implements java.io.Serializable {

	// Fields

	private String id;

	private Integer capacity;

	private Integer computerNum;

	private Integer peopleNum;

	private Double cost;

	private Set computers = new HashSet(0);

	private Set courselists = new HashSet(0);

	// Constructors

	/** default constructor */
	public Labroom() {
	}

	/** minimal constructor */
	public Labroom(String id, Integer capacity, Integer computerNum,
			Integer peopleNum, Double cost) {
		this.id = id;
		this.capacity = capacity;
		this.computerNum = computerNum;
		this.peopleNum = peopleNum;
		this.cost = cost;
	}

	/** full constructor */
	public Labroom(String id, Integer capacity, Integer computerNum,
			Integer peopleNum, Double cost, Set computers, Set courselists) {
		this.id = id;
		this.capacity = capacity;
		this.computerNum = computerNum;
		this.peopleNum = peopleNum;
		this.cost = cost;
		this.computers = computers;
		this.courselists = courselists;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Integer getCapacity() {
		return this.capacity;
	}

	public void setCapacity(Integer capacity) {
		this.capacity = capacity;
	}

	public Integer getComputerNum() {
		return this.computerNum;
	}

	public void setComputerNum(Integer computerNum) {
		this.computerNum = computerNum;
	}

	public Integer getPeopleNum() {
		return this.peopleNum;
	}

	public void setPeopleNum(Integer peopleNum) {
		this.peopleNum = peopleNum;
	}

	public Double getCost() {
		return this.cost;
	}

	public void setCost(Double cost) {
		this.cost = cost;
	}

	public Set getComputers() {
		return this.computers;
	}

	public void setComputers(Set computers) {
		this.computers = computers;
	}

	public Set getCourselists() {
		return this.courselists;
	}

	public void setCourselists(Set courselists) {
		this.courselists = courselists;
	}

}