package com.stuman.domain;

/**
 * Rechargelist generated by MyEclipse Persistence Tools
 */

public class Rechargelist implements java.io.Serializable {

	// Fields

	private RechargelistId id;

	private Student student;

	// Constructors

	/** default constructor */
	public Rechargelist() {
	}

	/** full constructor */
	public Rechargelist(RechargelistId id, Student student) {
		this.id = id;
		this.student = student;
	}

	// Property accessors

	public RechargelistId getId() {
		return this.id;
	}

	public void setId(RechargelistId id) {
		this.id = id;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

}