package com.stuman.domain;

import java.util.Date;

/**
 * RechargelistId generated by MyEclipse Persistence Tools
 */

public class RechargelistId implements java.io.Serializable {

	// Fields

	private String stuId;

	private Double money;

	private Date rechargetime;

	// Constructors

	/** default constructor */
	public RechargelistId() {
	}

	/** minimal constructor */
	public RechargelistId(String stuId, Double money) {
		this.stuId = stuId;
		this.money = money;
	}

	/** full constructor */
	public RechargelistId(String stuId, Double money, Date rechargetime) {
		this.stuId = stuId;
		this.money = money;
		this.rechargetime = rechargetime;
	}

	// Property accessors

	public String getStuId() {
		return this.stuId;
	}

	public void setStuId(String stuId) {
		this.stuId = stuId;
	}

	public Double getMoney() {
		return this.money;
	}

	public void setMoney(Double money) {
		this.money = money;
	}

	public Date getRechargetime() {
		return this.rechargetime;
	}

	public void setRechargetime(Date rechargetime) {
		this.rechargetime = rechargetime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RechargelistId))
			return false;
		RechargelistId castOther = (RechargelistId) other;

		return ((this.getStuId() == castOther.getStuId()) || (this.getStuId() != null
				&& castOther.getStuId() != null && this.getStuId().equals(
				castOther.getStuId())))
				&& ((this.getMoney() == castOther.getMoney()) || (this
						.getMoney() != null
						&& castOther.getMoney() != null && this.getMoney()
						.equals(castOther.getMoney())))
				&& ((this.getRechargetime() == castOther.getRechargetime()) || (this
						.getRechargetime() != null
						&& castOther.getRechargetime() != null && this
						.getRechargetime().equals(castOther.getRechargetime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getStuId() == null ? 0 : this.getStuId().hashCode());
		result = 37 * result
				+ (getMoney() == null ? 0 : this.getMoney().hashCode());
		result = 37
				* result
				+ (getRechargetime() == null ? 0 : this.getRechargetime()
						.hashCode());
		return result;
	}

}