package com.stuman.domain;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by MyEclipse Persistence Tools
 */

public class Student implements java.io.Serializable {

	// Fields

	private String id;

	private String name;

	private String password;

	private String departmentId;

	private String classes;

	private Double money;

	private Date registerTime;

	private Set rechargelists = new HashSet(0);

	private Set computeruses = new HashSet(0);

	// Constructors

	/** default constructor */
	public Student() {
	}

	/** minimal constructor */
	public Student(String id, String password, String departmentId,
			String classes, Double money) {
		this.id = id;
		this.password = password;
		this.departmentId = departmentId;
		this.classes = classes;
		this.money = money;
	}

	/** full constructor */
	public Student(String id, String name, String password,
			String departmentId, String classes, Double money,
			Date registerTime, Set rechargelists, Set computeruses) {
		this.id = id;
		this.name = name;
		this.password = password;
		this.departmentId = departmentId;
		this.classes = classes;
		this.money = money;
		this.registerTime = registerTime;
		this.rechargelists = rechargelists;
		this.computeruses = computeruses;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(String departmentId) {
		this.departmentId = departmentId;
	}

	public String getClasses() {
		return this.classes;
	}

	public void setClasses(String classes) {
		this.classes = classes;
	}

	public Double getMoney() {
		return this.money;
	}

	public void setMoney(Double money) {
		this.money = money;
	}

	public Date getRegisterTime() {
		return this.registerTime;
	}

	public void setRegisterTime(Date registerTime) {
		this.registerTime = registerTime;
	}

	public Set getRechargelists() {
		return this.rechargelists;
	}

	public void setRechargelists(Set rechargelists) {
		this.rechargelists = rechargelists;
	}

	public Set getComputeruses() {
		return this.computeruses;
	}

	public void setComputeruses(Set computeruses) {
		this.computeruses = computeruses;
	}

}