package com.stuman.domain;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Teacher generated by MyEclipse Persistence Tools
 */

public class Teacher implements java.io.Serializable {

	// Fields

	private String id;

	private String name;

	private String password;

	private String departmentId;

	private Date registerTime;

	private Set courselists = new HashSet(0);

	// Constructors

	/** default constructor */
	public Teacher() {
	}

	/** minimal constructor */
	public Teacher(String id, String password, String departmentId) {
		this.id = id;
		this.password = password;
		this.departmentId = departmentId;
	}

	/** full constructor */
	public Teacher(String id, String name, String password,
			String departmentId, Date registerTime, Set courselists) {
		this.id = id;
		this.name = name;
		this.password = password;
		this.departmentId = departmentId;
		this.registerTime = registerTime;
		this.courselists = courselists;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(String departmentId) {
		this.departmentId = departmentId;
	}

	public Date getRegisterTime() {
		return this.registerTime;
	}

	public void setRegisterTime(Date registerTime) {
		this.registerTime = registerTime;
	}

	public Set getCourselists() {
		return this.courselists;
	}

	public void setCourselists(Set courselists) {
		this.courselists = courselists;
	}

}