package com.stuman.domain;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * Teacher generated by MyEclipse Persistence Tools
 */

public class Teacher  implements java.io.Serializable {


    // Fields    

     private String id;
     private String name;
     private String password;
     private Date registerTime;
     private Set courselists = new HashSet(0);
     private Set courses = new HashSet(0);


    // Constructors

    /** default constructor */
    public Teacher() {
    }

	/** minimal constructor */
    public Teacher(String id, String password) {
        this.id = id;
        this.password = password;
    }
    
    /** full constructor */
    public Teacher(String id, String name, String password, Date registerTime, Set courselists, Set courses) {
        this.id = id;
        this.name = name;
        this.password = password;
        this.registerTime = registerTime;
        this.courselists = courselists;
        this.courses = courses;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    public Date getRegisterTime() {
        return this.registerTime;
    }
    
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    public Set getCourselists() {
        return this.courselists;
    }
    
    public void setCourselists(Set courselists) {
        this.courselists = courselists;
    }

    public Set getCourses() {
        return this.courses;
    }
    
    public void setCourses(Set courses) {
        this.courses = courses;
    }
   








}